config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/index'
  resources:'dishes'
  resources:'restaurants'
  root to:'dishes#index'

  get 'dishes/:id' => "dishes#showpage"
  get 'search'=>'dishes#search'
  get 'map'=> 'dishes#map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
	has_many :ratings
	has_and_belongs_to_many :restaurants
	
	has_attached_file :image, styles: {
       thumb: '100x100>',
       square: '200x200#',
       medium: '350x350>',
       pdf_preview: '600x600>'}, processors: [:thumbnail]
 validates_attachment :image, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)},
 attachment_size: { less_than: 5.megabytes }
end

app/models/dishes_restaurant.rb
class DishesRestaurant < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
	geocoded_by :location
	reverse_geocoded_by :latitude, :longitude
	after_validation :geocode
	has_many :restaurants
end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :dish
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_and_belongs_to_many :dishes
	belongs_to :location
end

app/models/restaurants_dish.rb
class RestaurantsDish < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
	has_many :dishes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def index
     @dishes = Dish.all
  end
  def show
    @dish = Dish.find(params[:id])
  end
  def search
    @locations = Location.all
    gon.locations = Location.all.select(:latitude,:longitude,:location)
    @taggings = Tagging.all
    @dishes_search  = Dish.where('name LIKE ?',"%#{params[:name]}%")
  if params[:filter]
   @dishes_search = Dish.order(params[:filter]).where('name LIKE ?',"%#{params[:name]}%")
  elsif params[:rating]
     @dishes_search = Dish.where('rating > ? ', params[:rating]).where('name LIKE ?',"%#{params[:name]}%")
  elsif params[:tagging]
    @dishes_search = Dish.where(tagging_id: params[:tagging]).where('name LIKE ?',"%#{params[:name]}%")
  elsif params[:min] and params[:max]
    @dishes_search =  Dish.where('price BETWEEN ? AND ?', params[:min], params[:max]).where('name LIKE ?',"%#{params[:name]}%")
  end
    respond_to do |format|
     format.html
     format.js
   end
  end
  private
  def dish_params
      params.require(:dish).permit(:name,:price,:rating,:image)
  end
  end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
 def index
 	if params[:search].present?
    @locations = Location.near(params[:search], 50, :order => :distance)
  else
    @locations = Location.all
  end
 end
 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
 def index
 end
 def show
   @restaurant = Restaurant.find(params[:id])
 end
 def map
 	  @location = Location.find(params[:id])
 	
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dishes/_list.html.erb
<% dishes.each_slice(2) do |items| %>
 <div class="row">
   <% items.each do |dish| %>
    <div class="col-lg-6 mt-3 ">
       <div class="hidd">
       		 <%= link_to(image_tag(dish.image.url(:original),class: " imagegrid_search"), dish_path(dish)) %>
       	</div>
        <h1 class="dish_name_text">
          <%= dish.name%>
        </h1>
          <%= dish.restaurants.find_each do |restaurant| %>
          <h4 class="restaurent_name">
          <%= link_to restaurant.name, restaurant_path(restaurant), class: "restaurant_text" %>
          </h4>
            <span class="price"><i class="fa fa-dollar"></i>
              <%= dish.price %></span>
           <span class="rating_count">
           	<%= image_tag('logos/heart.png')%>
            <span><%= dish.rating %></span>
            <h1 class="user_vote">1 vote</h1>
           </span>
          <div class="location">
            <div>
                <p><span><%= image_tag("logos/location.png",:class=>"locimage")%> </span><%= restaurant.location.location %></p>
              </div>
            </div>
         <% end %>
      </div>
     <% end %>
  </div>
<% end %>

app/views/dishes/index.html.erb
<div class="container-fluid">
  <%= image_tag("logos/landingimage.png",class: 'img-responsive landingimage')%>
</div>
	<div class="centered">
			<h1>What do you <em>really</em> feel like ?</h1>
	</div>
  <div class="searchcenter">
    <%= form_tag(search_path,method: :get ,enforce_utf8: false) do %>
        <%= text_field_tag :name,  nil,class: "landing_text",:placeholder =>'Chips and burgers' %>
        <span><%= image_tag('logos/search.png')%><%= submit_tag 'SEARCH', class: "search_btn",:name=>nil%></span>
      <% end %>
  </div>
 	<div class="center">
 		<h4 class="textincenter">TOP RATED DISHES</h4>
 	</div>
 <div class="container">
  <% @dishes.each_slice(3) do |dishitems| %>
    <div class="row grid">
    <% dishitems.each do |dish|%>
      <div class="col-lg-4">
        <div>
          <div class="hidd">
              <%= link_to(image_tag(dish.image.url(:original),class: "imagegrid"), dish_path(dish)) %>
          </div>
          <h3 class="dish_name_text">
            <%= dish.name%></h3>
            <%= dish.restaurants.find_each do |restaurant| %>
          <h4 class="restaurent_name">
            <%= link_to restaurant.name, restaurants_path(restaurant),class: "restaurant_text" %></h4>
            <span class="price"><i class="fa fa-dollar"></i>
              <%= dish.price %></span>
            <span class="rating_count">
            <%= image_tag('logos/heart.png',:class=>"heartlogo")%>
            <%= dish.rating %>
              <h1 class="user_vote">1 vote</h1>
            </span>
            <div class="location">
            <div>
              <p class="loctext"><span><%= image_tag("logos/location.png",:class=>"locimage")%>
                </span><%=restaurant.location.location%></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
  </div>
    <div class="center" id="show_more">
      <%= link_to "SEE MORE FOOD",dishes_path,method: :get, class: "loadmore",remote: true %>
    </div>
    <div class="container-fluid footer">
      <div class="row">
        <div class="col-lg-8">
          <div class="footertext">
        <p class="mt-5">Do more with the app.Download it today!</p>
      <%= image_tag("logos/googleplay.png",class: 'img-responsive image mb-5') %>
      <%= image_tag("logos/appstore.png",  class: 'img-responsive image mb-5') %>  
          </div>
        </div>
        <div class="col-lg-4">
          <%= image_tag("logos/phone.png",class: 'footer_img') %>
        </div>
      </div>
    </div>

app/views/dishes/index.js.erb
$('.index').html('<%= j render "dishes/indexall", dishes: @dishes%>');

app/views/dishes/search.html.erb
<div class="container-fluid">
<div class="row">
<div class="col-md-6 mt-5">
 <div class="row mt-5">
   <div class="col-md-4">
     <div class="row">
       <div class="col-md-4">
         <p class="filter_name_text">FILTER</p>
       </div>
       <div class="col-md-8">
          <%= select_tag :filter, options_for_select([["RATING","rating"],["PRICE","price"]]), {prompt: 'SORTBY', :name => "products_per_page", :class=>"form-control select_box1 ", id:"filter_sort", remote: true} %>
       </div>
     </div>
   </div>
   <div class="col-md-4">
      <%= select_tag :rating_filter, options_for_select([["3+",3],["4+",4],["5+",5]]),{prompt: 'ALL RATINGS', :name => "products_per_page", id:"rating_filter", :class=>"form-control select_box1",remote: true} %>
    </div>
   <div class="col-md-4">
      <div class="dropdown  w-25 select_box3">
          <div class="btn-light-outline dropdown-toggle dp_select" type="button" data-toggle="dropdown"><small id="check_boxid">ALL DIETARY REQUIREMENTS</small>
            <span class="caret"></span>
      </div>
        <div class="dropdown-menu">
            <div class="check_box_list select_box3">
              <%= @taggings.find_each do |tagging| %>
                <div class="check_box">
                  <%= check_box tagging.id,nil,:class=> "tag",:id=>tagging.id,:name=>tagging.name %>
                  <span class="tag_name"><%=tagging.name%></span>
                </div>
                <% end %>
              </div>
          </div>
      </div>
   </div>
   </div>
    <div class="row">
           <div class="col-md-2">
            <p class="filter_name_text"><%=@dishes_search.count%>RESULTS</p>
           </div><span id="min"></span>
           <div class="col-md-4 mt-2">
          <div id="the_slider" class="range">
          </div>
      </div><span id="max"></span>
         </div>
        <div class="row">
           <div class="container search_page_image">
            <% if @dishes_search.count > 0 %>
              <%= render 'dishes/list', dishes: @dishes_search %>
            <% else %>
            <p class="text-center">No result found</p>
              <% end %>
           </div>
         </div>
       </div>
       <div class="col-md-6 divmap"  id= "mapimage">
 
        </div>
     </div>
   </div>
</div>

app/views/dishes/search.js.erb
$('.search_page_image').html('<%= j render "dishes/list", dishes: @dishes_search %>');

app/views/dishes/show.html.erb
<div class="container-fluid ">
<div class="row rowcenter showpage">
   <div class="col-md-4  mt-5">
   <%= image_tag @dish.image.url(:medium), :class=>"show_image_logo mt-5" %>
     <strong class="showpage_dish_name" ><%= @dish.name %>
       <p class=" showpage_dish_price  text-center">Price :<%= @dish.price %></p>
     </strong>

      
    
     <%= @dish.restaurants.find_each do |restaurant| %>
     <div>
        <%= link_to restaurant.name, restaurant_path(restaurant), class: "showpage_res_text text-center mb-5" %> 
      </div>
      
     <% end %>
    </div>
   <div class="col-md-8 mt-5 hidd">
     <%= image_tag @dish.image.url(:original), :class=>"image_show_page" %>
   </div>
 </div>
</div>

app/views/layouts/_header.html.erb
 <div class="container-fluid navigation">
 	
 <nav class="navbar navbar-inverse navbar-fixed-top  ">
	<%= image_tag("logos/peppa.png",width:'150px',height:'45px',class: ' image navlogo')%>
	<div class="dropdown nav_select_location">
	  <button class="btn btn-light dropdown-toggle select_text" type="" data-toggle="dropdown"><span class="select_text">SELECT LOCATION</span>
	  <span class="caret"></span></button>
	  <ul class="dropdown-menu">
	    
	    <span><%= text_field_tag :login_aei %><%= image_tag("logos/search.png",:class=>"image")%></span>
	  </ul>
	</div>
	<div class="search">
	<span class="search">SEARCH</span>
	<span class="contact">CONTACTUS</span>
	</div>
</nav>
 </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodfie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <%= favicon_link_tag 'faviconpeppa.png' %>
    <meta charset="UTF-8">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
      <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBxBIfFGmL6adUEtytF2IYA10JZjQc5_sk&callback=initMap">
    </script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link  href = "https://cdnjs.cloudflare.com/ajax/libs/gmaps.js/0.4.25/gmaps.min.js.map" >
      
</head>
  <body>
    <div class="container-fluid ">
       <%= render 'layouts/header'%>
    </div>
    <%= yield %>
     </body>
</html>

app/views/locations/show.html.erb
<%= image_tag "http://maps.google.com/maps/AIzaSyBnOugOOHAXuU-bRYvZFRDpqzfftg-iyPs?/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>